Perofomance improvements, small css improvements, requested changes and tag addition to upload form
fdnd-agency/cmd pull request #120
Opened 2024-04-22 10:55 UTC by MokhtarAkle

# Description

# **Last big pull request!**

## Performance improvements

<details>
<summary>
Summary
</summary>  
  
To improve the performance of the website I've added many different improvements such as a more performant file format for all image files using avif. I've also added many improvements as suggested by a lighthouse test such as set widths and heights but also added lazy loading to all images using a svelte intersection observer to dynamically update what elements are visible.

</details>

<details>
<summary>
Related issues
</summary>  
#33 #34 #35 #32
</details>

<details>
<summary>
Screenshot
</summary>

Before: ![image](https://github.com/fdnd-agency/cmd/assets/45001009/d6af1fee-c2ef-4dd2-b9dc-6e4372469250)

After: ![image](https://github.com/fdnd-agency/cmd/assets/45001009/3ab7c670-5341-4f63-8a62-fff3eb0c872a)

</details>

## Small CSS improvements & requested changes

<details>
<summary>
Summary
</summary>  
  
Before having a sprint review it was important to add requested features to show these off properly and receive feedback. Many of these changes are small css changes along with a major overhaul in the back-end to change tags to the correct sub-tags. Ivar also joined the team during this pull and found many small issues that were hammered out by him. He also changed a lot of the structure to fix CSS validator errors.

</details>

<details>
<summary>
Related issues
</summary>  
#68 #69 #70 #71 #72 #114
</details>

<details>
<summary>
Screenshot
</summary>

![image](https://github.com/fdnd-agency/cmd/assets/45001009/e825ec3a-92cf-4717-b356-f14ffe098ff2)

</details>

## Tags addition to upload form

<details>
<summary>
Summary
</summary>  
 
The back-end data has been changed from regular tags to the appropriate sub-tags that correctly identify the different workforms. As requested by the client, I've added a way to select the newly added sub tags to the upload form and reflect these in the workform card that appears on the home page. The data is also correctly loaded into directus and the assigned sub tags get added to the workform object in directus.

</details>

<details>
<summary>
Related issues
</summary>
#101 #109
</details>

<details>
<summary>
Screenshot
</summary>

![image](https://github.com/fdnd-agency/cmd/assets/45001009/a4e51514-f8bc-4ef7-8582-34a2ff8a70a3)
![image](https://github.com/fdnd-agency/cmd/assets/45001009/801cb1a9-9678-4b8c-bec3-83680bd362f5)
![image](https://github.com/fdnd-agency/cmd/assets/45001009/78c42008-0179-442f-9530-480d2b493ad7)

</details>

# Link: https://grote-themas-sprint-19-rosy.vercel.app/

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

All changes are tested by both teammates and put through a lighthouse test and a responsiveness test.

- [x] User test
- [x] Accessibility test
- [x] Performance test
- [x] Responsive Design test

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] The code is accessible
- [x] The code is performant
- [x] The code is responsive
- [x] I have written meaningful commit messages
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README and/or Wiki)

2024-04-22 14:48 UTC, joostf commented
_"Last big pull request"_ 

😂

2024-04-23 06:37 UTC, ju5tu5 requested changes
Je nieuwe componenten zijn netter dan de oude. Heel veel comments gaan over onderverdeling in atoms, molecules en organisms. Probeer jezelf zo min mogelijk te herhalen en een duidelijke atomic design strategie te hanteren. Ook qua code stijl kan je files meer consistent opmaken, er wordt nu steeds een net andere approach gebruikt.

Ik stuur dit review in met _request changes_, kijk even goed welke dingen je als issue opneemt en welke zaken je voorlopig laat zitten. Ik weet dat jullie in afrondende fase zitten.

2024-04-23 06:37 UTC, ju5tu5 commented on src/routes/upload/+page.svelte
> +			<h1>Voeg een Kleine Werkvorm voor Grote Thema's toe</h1>
Is dit hoofdlettergebruik expliciet gevraagd?

2024-04-23 06:37 UTC, ju5tu5 commented on src/routes/upload/+page.server.ts
> +		console.log(werkvormSubtags)
console.log() weghalen voor productie

2024-04-23 06:37 UTC, ju5tu5 commented on src/routes/upload/+page.server.ts
Dit is een erg groot file geworden, kan het opgesplitst worden in modules?

2024-04-23 06:37 UTC, ju5tu5 commented on src/routes/[id]/+page.svelte
> +							<div class="single-tag" style="border-color: {tag.sub_tag_id.color};">
Is dit een atom?

2024-04-23 06:37 UTC, ju5tu5 commented on src/routes/+page.server.ts
Er worden directus aanvragen op pagina niveau gemaakt, is het niet handiger om met 'stores' te werken en de data niet elk paginabezoek op te halen? Scheelt een heleboel calls naar directus..

2024-04-23 06:37 UTC, ju5tu5 commented on src/lib/organisms/nav.svelte
> +				<img src="/images/icons/arrow-down.svg" alt="down arrow" id="feed-forward-img" class="unclicked">
Is dit een atom?

2024-04-23 06:37 UTC, ju5tu5 commented on src/lib/organisms/nav.svelte
Dit organisme kan verder opgedeeld worden in atomen en moleculen..

2024-04-23 06:37 UTC, ju5tu5 commented on src/lib/organisms/introSection.svelte
Dit organisme kan verder opgedeeld worden in atomen en moleculen..

2024-04-23 06:37 UTC, ju5tu5 commented on src/lib/organisms/introSection.svelte
> +        <img src="/images/werkvorm-animation-performant.gif" width="300" height="300" alt="animatie van werkvormen icoon" id="animation-image"/>
Is dit een atoom?

2024-04-23 06:37 UTC, ju5tu5 commented on src/lib/organisms/introSection.svelte
> +        <h1>Welkom op het platform Kleine werkvormen voor grote thema's</h1>
Is dit een atoom?

2024-04-23 06:37 UTC, ju5tu5 commented on src/lib/organisms/introSection.svelte
>      <div>
Is dit een molecuul?

2024-04-23 06:37 UTC, ju5tu5 commented on src/lib/organisms/UploadForm.svelte
Dit organisme kan verder opgedeeld worden in atomen en moleculen..

2024-04-23 06:37 UTC, ju5tu5 commented on src/lib/organisms/Header.svelte
> +    <img src="/images/hva-triangle.svg" alt="Triangle" class="graphic">
Is dit een atoom?

2024-04-23 06:37 UTC, ju5tu5 commented on src/lib/organisms/Header.svelte
Dit organisme kan verder opgedeeld worden in atomen en moleculen..

2024-04-23 06:37 UTC, ju5tu5 commented on src/lib/molecules/specialButton/index.ts
Waarom splits je in dit molecuul .ts en .svelte? Ik zie het pattern nergens anders..

2024-04-23 06:37 UTC, ju5tu5 commented on src/lib/molecules/specialButton/button.svelte
> +		<Icon iconSrc="/images/icons/arrow-right.svg"></Icon>
Is dit een atoom?

2024-04-23 06:37 UTC, ju5tu5 commented on src/lib/molecules/FullScreenButton.svelte
>          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrows-minimize" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stro
Definately atoom...

2024-04-23 06:37 UTC, ju5tu5 commented on src/lib/molecules/FullScreenButton.svelte
>          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrows-maximize" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stro
Atoom...

2024-04-23 06:37 UTC, ju5tu5 commented on src/lib/molecules/FullScreenButton.svelte
Dit molecuul kan verder opgedeeld worden in atomen en moleculen..

2024-04-23 06:37 UTC, ju5tu5 commented on src/lib/molecules/CheckFormField.svelte
Deze is netjes! Je gebruikt 3 atomen in een molecuul...

2024-04-23 06:37 UTC, ju5tu5 commented on src/lib/atoms/NavFilterList.svelte
Dit is geen atom, er gebeurt veel te veel. Is dit slim op te splitsen?

2024-04-23 12:51 UTC, joostf commented
@MokhtarAkle I'm merging this PR for it's to big to request changes. Please convert Justus' feedback into issues and prioritize them.

2024-04-23 12:51 UTC, merged