Experimenting with different authentication methods
fdnd-agency/cmd pull request #99
Opened 2024-03-04 13:19 UTC by MokhtarAkle

# Description

<details>
<summary>
Summary
</summary>  
  
At the moment I'm experimenting with different auth methods to implement a functional login system. My choices have been made based on available tutorials/ ease of use as I am a beginner when it comes to auth in web dev. As the most recommended auth library, Lucia is written in typescript, I've added TS to my project when needed. I've also added a local db and some minor changes to the project structure that shouldn't affect the rest of the project.
</details>

<details>
<summary>
Related issues
</summary>  
 #86 #88 #89 #90 
</details>

![image](https://github.com/fdnd-agency/cmd/assets/45001009/16eac0c4-cbdf-4db2-ab16-75bb33cd5840)

 **Link: https://grote-themas-sprint-19-rosy.vercel.app/**

Fixes: Nothing

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] User test
- [ ] Accessibility test
- [ ] Performance test
- [ ] Responsive Design test

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] The code is accessible
- [ ] The code is performant
- [ ] The code is responsive
- [x] I have written meaningful commit messages
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README and/or Wiki)

2024-03-05 10:15 UTC, joostf commented
@MokhtarAkle please discuss login strategy with @ju5tu5!

2024-03-05 13:06 UTC, MokhtarAkle commented
> @MokhtarAkle please discuss login strategy with @ju5tu5!

I had a small discussion with him and we agreed that the method should be decided by the assignment giver. Until I get in contact with him and hear his wishes I'll be continuing with this method for personal experience. In the next PR the method will be working as well so it seems to be a valid option!

2024-03-05 13:26 UTC, ju5tu5 commented
We talked about this indeed. I mentioned that i prefer magic link signin, especially because this doesn't have a difficult user management system. Of course, as you mention, the preference of your client is mandatory...

2024-03-05 13:43 UTC, MokhtarAkle commented
> We talked about this indeed. I mentioned that i prefer magic link signin, especially because this doesn't have a difficult user management system. Of course, as you mention, the preference of your client is mandatory...

From my (limited) experience the current method does not have a particulary difficult user management system seeing as I only store some basic user data and a session ID to validate the login. Of course I'm still planning to implement magic links as discussed although it'd probably be in a seperate repo for now so I don't start mixing things. Hopefully I'll be able to present both to the client for an easier choice.

2024-03-18 07:12 UTC, ju5tu5 commented on drizzleMigrations/meta/0000_snapshot.json
Hoort dit snapshot in de PR?

2024-03-18 07:13 UTC, ju5tu5 commented on drizzleMigrations/meta/_journal.json
Same here.. dit lijkt dummy data.. moet dat in een live omgeving?

2024-03-18 07:15 UTC, ju5tu5 commented on package.json
Ik zie drizzle (voor SQL right?) en MongoDB.. gebruik je 2 databases? Zo niet kan mongo weg denk ik...

2024-03-18 07:17 UTC, ju5tu5 commented on src/lib/atoms/NavFilterList.svelte
Beter...

2024-03-18 07:19 UTC, ju5tu5 commented on src/lib/atoms/SuperValidButton.svelte
Dit lijkt me meer een molecule.. omdat het een atom gebruikt..

2024-03-18 07:20 UTC, ju5tu5 commented on src/lib/atoms/inputfields/SelectField.svelte
Same.. meer een molecule.. er worden immers meerdere elementen genest...

2024-03-18 07:21 UTC, ju5tu5 commented on src/lib/atoms/inputfields/SuperValidInput.svelte
Duidelijk molecule..

2024-03-18 07:21 UTC, ju5tu5 commented on src/lib/atoms/specialButton/button.svelte
...molecule...

2024-03-18 07:23 UTC, ju5tu5 commented on src/lib/database/auth.server.ts
Hoe veilig is lucia? And again.. je verplicht je opdrachtgever een database te onderhouden met namen en emailadressen. Het is echt veel handiger om magic-link authenticatie te implementeren...

2024-03-18 07:27 UTC, ju5tu5 commented on src/lib/organisms/UploadForm.svelte
Wat mij betreft is dit bestand veeel te groot. Probeer het op te splitsen in logische atomic onderdelen in je lib..

2024-03-18 07:29 UTC, ju5tu5 commented on src/lib/validations/AuthZodSchemas.ts
De minimum lengte's moeten omhoog, dit is op dit moment niet veilig..

2024-03-18 07:30 UTC, ju5tu5 commented on src/routes/[id]/+page.svelte
Zet inlined SVG's ook in je lib..

2024-03-18 07:30 UTC, ju5tu5 commented on src/routes/[id]/+page.svelte
Bestand is ook best wel lang...

2024-03-18 07:31 UTC, ju5tu5 commented on svelte.config.js
Mooie aliases! Goed dat je die toevoegt..

2024-03-18 07:33 UTC, ju5tu5 requested changes
Je code stijl is best oke. Ik twijfel of Lucia definitief de juiste authenticatie is maar dat is een lopende discussie, het werkt voor nu. Je bestanden hebben de neiging nogal groot te worden en atomic design is niet overal even netjes toegepast, zou je daar nog eens naar kunnen kijken?

2024-03-18 13:49 UTC, MokhtarAkle commented on drizzleMigrations/meta/0000_snapshot.json
Nee zeker niet, drizzleMigrations is toegevoegd aan .gitignore en verwijderd uit de repo

2024-03-18 13:50 UTC, MokhtarAkle commented on drizzleMigrations/meta/_journal.json
Nee zeker niet, drizzleMigrations is toegevoegd aan .gitignore en verwijderd uit de repo

2024-03-18 13:56 UTC, MokhtarAkle commented on package.json
Alle ongebruikte dependencies zijn verwijderd en package.json en package-lock.json

2024-03-18 13:58 UTC, MokhtarAkle commented on src/lib/atoms/SuperValidButton.svelte
Veranderd naar molecule

2024-03-18 13:59 UTC, MokhtarAkle commented on src/lib/atoms/inputfields/SelectField.svelte
veranderd naar molecule

2024-03-18 14:00 UTC, MokhtarAkle commented on src/lib/atoms/inputfields/SuperValidInput.svelte
veranderd naar molecule

2024-03-18 14:01 UTC, MokhtarAkle commented on src/lib/atoms/specialButton/button.svelte
veranderd naar molecule en haal icon op van atom

2024-03-18 14:04 UTC, MokhtarAkle commented on src/lib/database/auth.server.ts
Over veiligheid kan ik niet heel veel zeggen maar gebaseerd op internet resultaten is het op z'n minst veilig om te gebruiken als dev. De developer ervan is ook erg actief en commit bijna elke dag naar de Lucia repo. Na gesprek met de opdrachtgever snappen we beide niet wat voor onderhoud er nodig is voor de database, uitleg zou gewardeerd zijn. Magic-link staat nog steeds in de planning als een could have dus als er tijd voor is zal ik het proberen te implementeren.

2024-03-18 14:06 UTC, MokhtarAkle commented on src/lib/organisms/UploadForm.svelte
Validator uit de uploadform gehaald en in eigen component gestopt, verder splitsing lijkt mij niet logisch maar hoor graag feedback hierop.

2024-03-18 14:07 UTC, MokhtarAkle commented on src/lib/validations/AuthZodSchemas.ts
Na advies van Cyd de minimum naam lengte verlaagd naar 1 en de minimum wachtwoord lengte verhoogd naar 10

2024-03-18 14:21 UTC, MokhtarAkle commented on src/routes/[id]/+page.svelte
Inlined SVG verwijderd en img met src toegevoegd, zal nog even kijken naar het bestand voor mogelijke componenten

2024-03-18 14:22 UTC, MokhtarAkle commented on svelte.config.js
Bedankt! Zal er voor zorgen dat ze overal gebruikt worden waar dit logisch is!

2024-03-27 11:17 UTC, RayanSp reviewed
Code ziet er voor zo ver ik kan zien prima uit.

2024-03-27 11:17 UTC, RayanSp commented on src/routes/login/+page.svelte
> +	<section>
Je zou ipv een section en een h1, gebruik kunnen maken van een <fieldset> met daarin een <legend>.

2024-03-27 12:43 UTC, merged